version: '3'

services:

  sql-server:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    ports:
      - "1789:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "<password>"
    volumes:
      - ~/vols/mssql/:/var/opt/mssql
      - ./copy:/root/init
    working_dir: /root/init
    command: sh -c 'chmod +x ./entrypoint.sh; ./entrypoint.sh & /opt/mssql/bin/sqlservr;'

  insider-scraper:
    build: .
    container_name: insider-scraper
    volumes:
      - insider-scraper-volume:/root/Projects/
    tty: true
    entrypoint: bash
    depends_on:
      - sql-server

volumes:
  insider-scraper-volume: